### PR TITLE
Fix godoc links at top of README

### PR DESCRIPTION
**Pull request by dsymonds**
They were pointing at v1 whereas the rest of the doc points at v2.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Thanks!

Could you please add the signed-off-by (DCO check).

**Comment by dsymonds** [comment]
I hereby disclaim any copyright interest in this change, and assign it to
the project.

**Comment by vmarkovtsev** [comment]
Thanks again. This is OK from the legal point of view and I can merge this right now, but let me ask first if it is possible to execute

```
git commit --amend --no-edit --signoff
git push -f origin patch-1
```

I see that you used the GitHub web UI to create the fix, so I guess it will be a pain. At the same time, when we will do license audit in the future, we will see that all the external contributions are signed-off without having to go to this specific PR page.

**Comment by dsymonds** [comment]
Yeah, understand. A bit annoying, but done.

**Pull request merged**
