### PR TITLE
Update to go-git 4.7.0

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Thanks to @frapposelli in https://github.com/src-d/go-license-detector/pull/63

Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Interesting: if I run `go mod tidy`, the tests fail even on the same go-git version.

**Comment by frapposelli** [comment]
Hi @vmarkovtsev, thanks for digging through this, I noticed you removed `go.sum` with this PR, consider keeping it[0]

[0]: https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

**Comment by vmarkovtsev** [comment]
I am debugging right now, once I figure out the important dep, I will let you know and close this PR.

Regarding `go.sum`, every time somebody merely builds a project with several deps, that file gets updated. I do many code reviews every week, and that cognitive noise has finally bent me over. I believe that this is against best practices, but my mental health is more important...

**Comment by vmarkovtsev** [comment]
I bet this is happening because of https://github.com/sergi/go-diff/pull/90 is not included into `sergi/go-diff 1.0.0`

**Comment by frapposelli** [comment]
If that is the culprit you can pin that dependency to a specific hash like
```
$ go get github.com/sergi/go-diff@da645544ed44df016359bd4c0e3dc60ee3a0da43
```

**Pull request merged**
